apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/kyleee0522/edu_baseinfo
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: JAVA_TOOL_OPTIONS 
              value: "-Delastic.apm.server_url=http://apm-server.edu1.svc.cluster.local:8200 -Delastic.apm.environment=dev -Dservice_name=backend -Delastic.apm.secret_token="    ## secret_token 값은 비워둠
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: argo-secret
